import Groq from "groq-sdk";

// Lazy + cached on globalThis, same pattern as src/db/client.ts's MongoClient
// caching -- avoids re-instantiating on every Next.js dev-mode hot reload.
const globalForGroq = globalThis as unknown as { _groqClient?: Groq };

/** Null when GROQ_API_KEY isn't set, so callers can fall back to the static seed pool. */
export function getGroqClient(): Groq | null {
  if (!process.env.GROQ_API_KEY) {
    return null;
  }
  if (!globalForGroq._groqClient) {
    globalForGroq._groqClient = new Groq({ apiKey: process.env.GROQ_API_KEY });
  }
  return globalForGroq._groqClient;
}

/**
 * Models per lane, in preference order.
 *
 * `llama-3.3-70b-versatile` used to serve everything. It was decommissioned
 * under us: every call returned 404 model_not_found, and since that is not a
 * rate-limit response nothing backed off, so each request paid a wasted round
 * trip and then fell through to Gemini. Every scenario in the product was being
 * generated by the fallback provider alone, which promptly exhausted its own
 * quota. The dual-provider design had become single-provider without a single
 * failing test.
 *
 * More than one, because each model is its own 8,000-token bucket: when a lane's
 * primary is exhausted, the next entry is a *fresh* budget rather than a wait.
 * Falling back within Groq before reaching for Gemini matters more than it
 * looks -- Gemini's free tier turned out to allow 20 requests per day
 * (quotaId GenerateRequestsPerDayPerProjectPerModel-FreeTier), which is not a
 * fallback so much as a rounding error. Groq allows 1,000 per day per model.
 *
 * Primary assignment is by difficulty, not cost: `refine` emits the strict JSON
 * and the honest cue severities, which is the stage that has to be right, so it
 * leads with the strongest model. Drafting prose is the easy half. Lists overlap
 * deliberately -- a model that is somebody's primary is still a perfectly good
 * second choice for another lane, and it is a different bucket either way.
 */
export const GROQ_LANE_MODELS = {
  draft: ["openai/gpt-oss-20b", "groq/compound-mini"],
  refine: ["openai/gpt-oss-120b", "openai/gpt-oss-20b"],
  chat: ["qwen/qwen3.6-27b", "openai/gpt-oss-20b"],
} as const satisfies Record<string, readonly string[]>;

/**
 * Every model above was checked against a demanding nested-JSON prompt before
 * being listed, because passing a trivial one proves nothing.
 * `qwen/qwen3.6-27b` returned a valid `{"ok":true}` for a toy request and then
 * failed every real generation with `json_validate_failed` and an *empty*
 * failed_generation -- so it stays on `chat`, which is the one lane that does
 * not ask for JSON, and never appears in a lane that does.
 *
 * `openai/gpt-oss-safeguard-20b` also handles the JSON fine but is a safety
 * model, and the draft stage's whole job is authoring a convincing phishing
 * pretext. Not worth discovering its refusal behaviour in production.
 *
 * gpt-oss-20b appearing as draft's primary and refine's fallback is deliberate
 * and harmless: it is one bucket, the limiter serialises it, and refine only
 * reaches for it once its own primary is exhausted.
 */

/**
 * Reserved completion budget per lane.
 *
 * Left unbounded, one runaway completion can eat an entire minute of an
 * 8,000-token bucket, and admission control cannot price a call it has no
 * ceiling for.
 *
 * The draft cap started at 1,400 and that was too tight: a longer email body ran
 * past it, the completion was truncated mid-object, and Groq's JSON mode
 * rejected the result with `json_validate_failed` -- which reads like a prompt
 * problem, not a token cap. Measured draft usage is around 1,700 tokens total
 * including roughly 500 of prompt, so the ceiling now leaves real headroom
 * rather than sitting just above the average.
 */
export const GROQ_LANE_MAX_TOKENS = {
  draft: 2_400,
  refine: 2_400,
  chat: 800,
} as const;

/**
 * The default lane, for callers that have no opinion.
 *
 * `chat` rather than a generation lane: an unlabelled call is far more likely to
 * be someone waiting on a reply than a background top-up, and it keeps
 * unlabelled traffic off the buckets the pipeline depends on.
 */
export const GROQ_DEFAULT_LANE = "chat";
