import type { InsertScenario, SpecConventions } from "@/db";

// Raw seed content -- scenarioId, source, and the spec-convention fields
// (metadata/timestamps) are stamped in src/server/seed.ts at insert time,
// not part of this static data.
type SeedScenario = Omit<InsertScenario, "scenarioId" | "source" | keyof SpecConventions>;

// Cue ids and severity match the shared phishaware-db schema spec's 8-value
// `cueType` enum + numeric severity (see src/server/cues.ts). Severity scale:
// 1 = low, 2 = medium, 3 = high. Difficulty is 1-5 per the spec (mapped from
// the old easy/medium/hard labels: easy=1, medium=3, hard=5).
export const SEED_SCENARIOS: SeedScenario[] = [
  // Onboarding pool (5)
  {
    vector: "email",
    isPhish: true,
    sender: "IT Support <helpdesk@corp-secure-mail.net>",
    subject: "Action Required: Your password expires today",
    body: "Dear user,\n\nOur records show your account password expires in a few hours. To avoid losing access, verify your credentials immediately using the link below.\n\nThank you,\nIT Support Team",
    links: [{ text: "http://corp-secure-mail.net/reset?id=88213", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 3, explanation: "The company's real domain doesn't match 'corp-secure-mail.net'." },
      { type: "urgency_language", severity: 2, explanation: "Claims your password expires 'today' to rush you." },
      { type: "credential_request", severity: 3, explanation: "Asks you to 'verify your credentials' via a link." },
      { type: "generic_greeting", severity: 1, explanation: "Addresses you as 'Dear user' instead of your name." },
    ],
    difficulty: 1,
    isOnboarding: true,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "The Daily Brew <news@dailybrew.com>",
    subject: "You're subscribed! Here's what to expect",
    body: "Hi there,\n\nThanks for subscribing to The Daily Brew. Every Monday you'll get a short roundup of the week's top stories in your inbox. You can update your preferences or unsubscribe any time from the link in the footer.\n\nSee you Monday,\nThe Daily Brew Team",
    links: [{ text: "https://dailybrew.com/preferences", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: true,
  },
  {
    vector: "email",
    isPhish: true,
    sender: "Alex Chen (CEO) <alex.chen@corp-exec-office.com>",
    subject: "Quick favor - need this handled discreetly",
    body: "Hey,\n\nI'm stuck in back-to-back meetings and need you to pick up $500 in gift cards for a client gift before 3pm. I'll pay you back. Please keep this between us for now, and reply once it's done.\n\nThanks,\nAlex",
    links: [],
    attachments: [],
    cues: [
      { type: "urgency_language", severity: 3, explanation: "Demands action before a hard deadline (3pm)." },
    ],
    difficulty: 3,
    isOnboarding: true,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "Northline Bank <notifications@northlinebank.com>",
    subject: "Your monthly statement is ready",
    body: "Hello,\n\nYour account statement for last month is now available in your Northline Bank online banking portal. Log in through the app or northlinebank.com as usual to view it.\n\nNorthline Bank",
    links: [{ text: "https://northlinebank.com/login", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: true,
  },
  {
    vector: "email",
    isPhish: true,
    sender: "Rewards Center <winner@prizes-notify.info>",
    subject: "Congratulations! You've won a $1,000 gift card",
    body: "Dear Winner,\n\nYou have been randomly selected to receive a $1,000 gift card! Claim your prize within 24 hours by confirming your details at the link below.\n\nRewards Center",
    links: [{ text: "http://prizes-notify.info/claim?winner=true", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "mismatched_link", severity: 2, explanation: "The domain 'prizes-notify.info' isn't a recognizable retailer." },
      { type: "generic_greeting", severity: 1, explanation: "Addressed to 'Dear Winner' instead of a real name." },
      { type: "urgency_language", severity: 2, explanation: "24-hour claim deadline pressures quick action." },
    ],
    difficulty: 1,
    isOnboarding: true,
  },
  // General practice pool
  {
    vector: "email",
    isPhish: true,
    sender: "Delivery Notice <tracking@parcel-expresss.com>",
    subject: "Your package could not be delivered",
    body: "Hi,\n\nWe attempted to deliver your package but no one was available. Please confirm your address and pay a small redelivery fee within 48 hours to avoid your parcel being returned.\n\nParcel Express",
    links: [{ text: "http://parcel-expresss.com/redeliver", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 2, explanation: "'parcel-expresss.com' (triple s) isn't a real courier domain." },
      { type: "urgency_language", severity: 2, explanation: "48-hour deadline to act." },
      { type: "credential_request", severity: 2, explanation: "Asks for a payment/address confirmation through a link." },
      { type: "spelling_grammar", severity: 1, explanation: "Odd extra letter in the domain name." },
    ],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: true,
    sender: "Document Share <no-reply@docushare-files.co>",
    subject: "A file has been shared with you",
    body: "Hello,\n\nA document titled 'Q3_Contract_Final' has been shared with you. Click below to view and sign.\n\nThank you.",
    links: [{ text: "http://docushare-files.co/view/9931", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "generic_greeting", severity: 1, explanation: "No sender name or personal detail." },
      { type: "mismatched_link", severity: 3, explanation: "Unfamiliar file-sharing domain, not a known provider." },
      { type: "sender_domain", severity: 2, explanation: "Not a recognized document-sharing service." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "Priya Nair <priya.nair@yourcompany.com>",
    subject: "Team meeting moved to 3pm",
    body: "Hi all,\n\nQuick heads up -- I'm moving our sync from 2pm to 3pm today since I have a conflicting call. Same room. Let me know if that doesn't work for anyone.\n\nThanks,\nPriya",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: true,
    sender: "Security Alert <alert@secure-northlinebank.com>",
    subject: "Unusual sign-in detected on your account",
    body: "We noticed a sign-in from an unrecognized device. If this wasn't you, your account may be locked within 24 hours. Verify your identity now to keep your account active.",
    links: [{ text: "http://secure-northlinebank.com/verify", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 3, explanation: "'secure-northlinebank.com' is not the bank's real domain." },
      { type: "urgency_language", severity: 3, explanation: "Threatens account lock within 24 hours." },
      { type: "credential_request", severity: 3, explanation: "Asks you to 'verify your identity' via a link." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "Cloud Editor <updates@cloudeditorapp.com>",
    subject: "New version available with faster load times",
    body: "Hi,\n\nWe've shipped an update that improves load times by 30% and fixes a few sync bugs. Update from within the app whenever you get a chance -- no action needed right now.\n\nThe Cloud Editor Team",
    links: [{ text: "https://cloudeditorapp.com/changelog", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: true,
    sender: "HR Benefits <benefits@hr-enroll-portal.com>",
    subject: "Confirm your 2026 benefits enrollment now",
    body: "Your open enrollment window closes tonight. Log in immediately with your employee ID and password to keep your current benefits, or they will be automatically dropped.",
    links: [{ text: "http://hr-enroll-portal.com/login", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "credential_request", severity: 3, explanation: "Asks for employee ID and password directly." },
      { type: "urgency_language", severity: 3, explanation: "'Closes tonight' pressures an immediate login." },
      { type: "sender_domain", severity: 2, explanation: "Not your company's real HR system domain." },
    ],
    difficulty: 5,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: true,
    sender: "Jordan Lee <jordan.lee@yourcompany-corp.com>",
    subject: "quick favor before you head out",
    body: "hey are you at your desk? need you to send me the wire transfer details for the client asap, kind of urgent. can't talk right now, just reply here",
    links: [],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 2, explanation: "The domain 'yourcompany-corp.com' doesn't match the real company domain." },
      { type: "urgency_language", severity: 3, explanation: "'asap' and 'can't talk right now' pressure a fast, unverified reply." },
    ],
    difficulty: 5,
    isOnboarding: false,
  },
  // SMS practice pool (fallback used only if the Groq generator is
  // unavailable -- "subject" is unused for this vector, texts don't have
  // one, so it's left blank rather than faked).
  {
    vector: "sms",
    isPhish: true,
    sender: "+1 (302) 555-0148",
    subject: "",
    body: "USPS: Your package has a $2.99 customs fee due. Pay now to avoid return to sender: usps-tracking.info/pay",
    links: [{ text: "usps-tracking.info/pay", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "mismatched_link", severity: 2, explanation: "'usps-tracking.info' isn't USPS's real domain (usps.com)." },
      { type: "urgency_language", severity: 2, explanation: "Threatens the package will be returned if you don't pay immediately." },
    ],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: false,
    sender: "+1 (617) 555-0102",
    subject: "",
    body: "Reminder: Your dentist appointment with Dr. Alvarez is tomorrow at 10:00 AM. Reply C to confirm or call the office to reschedule.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: true,
    sender: "Chase-Alerts",
    subject: "",
    body: "Chase: We noticed unusual activity on your card ending in 4471. Verify now to avoid a temporary hold: chse-secure.com/verify",
    links: [{ text: "chse-secure.com/verify", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 2, explanation: "'chse-secure.com' misspells Chase's real domain." },
      { type: "urgency_language", severity: 2, explanation: "Warns of an account hold unless you act now." },
      { type: "credential_request", severity: 2, explanation: "Asks you to 'verify' your account through the link." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: false,
    sender: "28107",
    subject: "",
    body: "Your Google verification code is 482913. Don't share this code with anyone.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: true,
    sender: "+1 (415) 555-0199",
    subject: "",
    body: "Congrats! You've been selected for a free $500 Amazon gift card. Claim before midnight: amzn-rewards.co/claim",
    links: [{ text: "amzn-rewards.co/claim", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "mismatched_link", severity: 2, explanation: "'amzn-rewards.co' isn't an Amazon domain." },
      { type: "urgency_language", severity: 2, explanation: "'Claim before midnight' pressures a fast click." },
    ],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: true,
    sender: "IT-Helpdesk",
    subject: "",
    body: "IT Helpdesk: We detected repeated login attempts on your account. Reply with the 6-digit code we just sent to cancel the lockout.",
    links: [],
    attachments: [],
    cues: [
      { type: "credential_request", severity: 3, explanation: "Asks you to relay a one-time code, effectively handing over MFA access." },
      { type: "urgency_language", severity: 2, explanation: "Implies an account lockout is imminent." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  // Voice-call practice pool (fallback used only if live generation is
  // unavailable -- "subject" is unused for this vector, calls don't have one).
  {
    vector: "voice",
    isPhish: true,
    sender: "Bank Security",
    subject: "",
    body: "Caller: Hi, this is Northline Bank Fraud Prevention.\nCaller: We detected unusual activity and need to secure your account right now.\nCaller: Please confirm your online banking password so I can cancel the lock.\nCaller: If we don't verify in the next few minutes, your account will be frozen.",
    links: [],
    attachments: [],
    cues: [
      { type: "urgency_language", severity: 3, explanation: "Pushes immediate action with threats of account freeze." },
      { type: "credential_request", severity: 3, explanation: "Directly asks for your banking password over the phone." },
      { type: "generic_greeting", severity: 1, explanation: "Uses a broad institutional intro instead of verifying your identity safely." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "voice",
    isPhish: false,
    sender: "+1 (617) 555-0129",
    subject: "",
    body: "Caller: Hi, this is Mia from Lakeside Dental.\nCaller: Just a reminder that your cleaning is tomorrow at 10:00 AM.\nCaller: If you need to reschedule, call us back at the number on your appointment card.\nCaller: Thanks, and see you tomorrow.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: false,
  },
  {
    vector: "voice",
    isPhish: true,
    sender: "IT Helpdesk",
    subject: "",
    body: "Caller: Hey, this is IT Support.\nCaller: We're fixing a major VPN outage and need to re-authenticate your account now.\nCaller: Read me your one-time MFA code and we'll restore access immediately.\nCaller: This is faster than the portal, and your access will expire if you wait.",
    links: [],
    attachments: [],
    cues: [
      { type: "credential_request", severity: 3, explanation: "Requests a one-time MFA code, which should never be shared." },
      { type: "urgency_language", severity: 2, explanation: "Claims your access will expire if you don't comply immediately." },
      { type: "generic_greeting", severity: 1, explanation: "No verification details beyond a vague 'IT Support' identity." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "voice",
    isPhish: false,
    sender: "City Utilities",
    subject: "",
    body: "Caller: Hello, this is the City Utilities automated reminder.\nCaller: Your payment is scheduled and no action is needed.\nCaller: For account questions, please use the phone number listed on your monthly statement.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 1,
    isOnboarding: false,
  },
  // QR, social and web pools. Every other vector shipped with static content;
  // these three were added to the generator and the UI without any, so picking
  // them from the practice filter hit an empty pool, fell through to blocking
  // live generation, and returned "No practice scenarios available" whenever a
  // provider was rate limited or unconfigured. A vector offered in the UI has to
  // work with no network at all.
  {
    vector: "qr",
    isPhish: true,
    sender: "Facilities Management",
    subject: "Parking permit renewal -- action required",
    body: "All staff parking permits expire on Friday. Scan the code below to renew yours. Vehicles without a valid permit from Monday will be issued a 60 charge by the site operator.",
    links: [{ text: "https://staff-permits-renew.info/login", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "suspicious_qr", severity: 3, explanation: "A printed code is the one link you cannot read before following it." },
      { type: "mismatched_link", severity: 3, explanation: "The code resolves to staff-permits-renew.info, which is not your employer's domain." },
      { type: "urgency_language", severity: 2, explanation: "A Friday deadline with a named charge attached." },
      { type: "credential_request", severity: 3, explanation: "The destination is a login page asking for work credentials." },
    ],
    difficulty: 2,
    isOnboarding: false,
  },
  {
    vector: "qr",
    isPhish: true,
    sender: "IT Service Desk",
    subject: "Multi-factor authentication reset",
    body: "We are migrating staff accounts to a new authenticator app this week. Scan to re-enrol your device. Accounts not re-enrolled by 5pm Thursday will be locked until a helpdesk ticket is raised.",
    links: [{ text: "https://mfa-reenrol.security-portal.co/start", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "suspicious_qr", severity: 3, explanation: "Re-enrolling authentication is never done from a printed square." },
      { type: "mismatched_link", severity: 3, explanation: "security-portal.co owns the destination, not your employer." },
      { type: "urgency_language", severity: 3, explanation: "Threatens a lockout at a specific hour." },
      { type: "generic_greeting", severity: 1, explanation: "Addressed to nobody, posted for anyone walking past." },
    ],
    difficulty: 4,
    isOnboarding: false,
  },
  {
    vector: "qr",
    isPhish: false,
    sender: "Building Reception",
    subject: "Visitor wifi",
    body: "Guest network: NORTHLINE-GUEST. Scan for the joining details, or ask at the desk and we will print them for you. The code is reprinted each month with the new password.",
    links: [{ text: "https://northline.example/guest-wifi", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 2,
    isOnboarding: false,
  },
  {
    vector: "social",
    isPhish: true,
    sender: "Dana Whitfield (@d.whitfield-recruiting)",
    subject: "",
    body: "Hi! I came across your profile and you're a strong match for a senior role we're hiring for -- fully remote, and the band is well above what you're on now. I can send the spec over. Easier to chat on WhatsApp, my number is in my profile. Could you fill in this short form first so I can register your interest before Friday?",
    links: [{ text: "https://talent-verify.co/apply/register", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 2, explanation: "The handle names no employer you can go and verify." },
      { type: "mismatched_link", severity: 3, explanation: "Applications belong on the employer's own careers site, not talent-verify.co." },
      { type: "urgency_language", severity: 2, explanation: "A Friday deadline arriving before the job description." },
      { type: "credential_request", severity: 2, explanation: "A form to complete before anyone has said what the role is." },
    ],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "social",
    isPhish: true,
    sender: "Marcus Bell (@marcus.bell.finance)",
    subject: "",
    body: "Hey, it's Marcus from the finance team -- I'm locked out of my work account and I'm on leave so I can't call IT. Could you forward me the verification code that just came to your phone? I'll sort it properly on Monday, just need to approve one payment run today.",
    links: [],
    attachments: [],
    cues: [
      { type: "credential_request", severity: 3, explanation: "Asks you to forward a verification code, which is what logs someone in." },
      { type: "urgency_language", severity: 3, explanation: "A payment run today, with the proper route conveniently unavailable." },
      { type: "sender_domain", severity: 2, explanation: "A colleague contacting you from a personal social account rather than at work." },
    ],
    difficulty: 4,
    isOnboarding: false,
  },
  {
    vector: "social",
    isPhish: false,
    sender: "Priya Raman (@priya.raman)",
    subject: "",
    body: "Hi -- we met at the security meetup last month, you spoke about phishing training. I'm writing up a short piece on it for our team newsletter. No rush at all, and happy to keep it here rather than move to email if that's easier. Would you mind if I quoted you?",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "web",
    isPhish: true,
    sender: "https://login.microsoftonline.com.session-verify.net/auth",
    subject: "Sign in to continue",
    body: "Your session has expired. Please confirm your credentials to restore access to your mailbox and files.",
    links: [{ text: "Forgot your password?", isSuspicious: false }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 3, explanation: "Read right to left: session-verify.net owns this page. Everything before it is a subdomain." },
      { type: "credential_request", severity: 3, explanation: "A password form reached by following a link." },
      { type: "urgency_language", severity: 1, explanation: "'Your session has expired' is unfalsifiable and plausible at any moment." },
    ],
    difficulty: 4,
    isOnboarding: false,
  },
  {
    vector: "web",
    isPhish: true,
    sender: "https://micros0ft-billing.com/account/renew",
    subject: "Your subscription payment failed",
    body: "We could not process your most recent payment. Update your card details to keep your licence active. Services will be suspended after 48 hours.",
    links: [{ text: "Contact billing support", isSuspicious: true }],
    attachments: [],
    cues: [
      { type: "sender_domain", severity: 3, explanation: "A zero in place of the o, on a domain that is not Microsoft's." },
      { type: "credential_request", severity: 3, explanation: "Asks for card details on a page you arrived at from a link." },
      { type: "urgency_language", severity: 2, explanation: "A 48-hour suspension window." },
    ],
    difficulty: 2,
    isOnboarding: false,
  },
  {
    vector: "web",
    isPhish: false,
    sender: "https://northlinebank.com/login",
    subject: "Sign in to online banking",
    body: "Enter your customer number to continue. We will never ask for your full password or a one-time code by phone, email or text.",
    links: [{ text: "Forgotten your customer number?", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
  // Legitimate mail, to bring the static library to an even split.
  //
  // The pool was 20 phishing to 11 legitimate, so a learner who answered
  // "phishing" every round scored about 65% without exercising any judgement,
  // and the stream read as relentlessly hostile rather than like a real inbox to
  // be sorted. Recognising safe mail is half the skill: somebody who reports
  // every invoice is as expensive to their employer as somebody who reports
  // none.
  //
  // These are deliberately *not* obviously safe. Each one carries a feature that
  // looks like a red flag until it is checked -- a deadline, a link, an
  // attachment, an unfamiliar sender -- because a legitimate scenario a learner
  // can dismiss at a glance teaches nothing.
  {
    vector: "email",
    isPhish: false,
    sender: "Workday <no-reply@myworkday.com>",
    subject: "Action needed: complete your annual compliance training by Friday",
    body: "Hi {{firstName}},\n\nYour annual compliance module is due Friday. It takes about 20 minutes and you can pause and resume.\n\nIf you have already completed it, no action is needed. You can also reach it from the Workday tile on the intranet rather than this link.\n\nHR Operations",
    links: [{ text: "https://myworkday.com/learning/assigned", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "Priya Raman <priya.raman@northline.example>",
    subject: "Invoice for October, PO 44817",
    body: "Hi {{firstName}},\n\nAttached is the October invoice against PO 44817, same terms as last quarter. Bank details are unchanged from the ones already on file.\n\nIf anything looks off, call me on the number in the directory rather than replying here.\n\nPriya",
    links: [],
    attachments: [{ name: "invoice-oct-PO44817.pdf", isSuspicious: false }],
    cues: [],
    difficulty: 4,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "IT Service Desk <servicedesk@northline.example>",
    subject: "Your laptop will restart tonight to finish updates",
    body: "Hi {{firstName}},\n\nYour laptop has updates waiting that need a restart. It will restart automatically at 22:00 tonight if you have not done it yourself by then.\n\nWe will never ask you for your password to install an update. If anyone does, that is worth reporting.\n\nIT Service Desk",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 2,
    isOnboarding: false,
  },
  {
    vector: "email",
    isPhish: false,
    sender: "Northline Travel <bookings@northline-travel.example>",
    subject: "Your itinerary for 14 November is confirmed",
    body: "Hi {{firstName}},\n\nYour trip is booked. Departure 14 November, 07:40, returning the 16th. The full itinerary and your seat are in the attachment.\n\nChanges go through the travel desk on the intranet, not by replying to this address.\n\nNorthline Travel",
    links: [],
    attachments: [{ name: "itinerary-14nov.pdf", isSuspicious: false }],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: false,
    sender: "NORTHLINE",
    subject: "",
    body: "Your sign-in code is 481902. We will never ask you to share it. If you did not request it, ignore this message.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "sms",
    isPhish: false,
    sender: "DPD",
    subject: "",
    body: "Your parcel 8842-JQ is out for delivery today between 13:00 and 15:00. Track or reschedule in the DPD app.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 4,
    isOnboarding: false,
  },
  {
    vector: "qr",
    isPhish: false,
    sender: "Northline Facilities",
    subject: "Meeting room 3C: report a fault",
    body: "Something not working in this room? Scan to raise a ticket, or call extension 2140. Printed and posted by Facilities; the code goes to the internal service desk.",
    links: [{ text: "https://northline.example/servicedesk/room/3c", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
  {
    vector: "social",
    isPhish: false,
    sender: "Marcus Bell (@marcusbell)",
    subject: "",
    body: "Hi, we worked together on the Halden migration in 2023. I have moved to a security team and we are hiring; happy to put your name forward if you are interested. No rush, and no need to send anything over. My work email is on my profile if you would rather use that.",
    links: [],
    attachments: [],
    cues: [],
    difficulty: 4,
    isOnboarding: false,
  },
  {
    vector: "web",
    isPhish: false,
    sender: "https://northline.example/sso/login",
    subject: "Sign in with your Northline account",
    body: "You were redirected here to continue. This is your organization's own sign-in page; check the address before entering anything, as you should on any page that asks for a password.",
    links: [{ text: "Trouble signing in?", isSuspicious: false }],
    attachments: [],
    cues: [],
    difficulty: 3,
    isOnboarding: false,
  },
];
