import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * Flat config (ESLint 9). The old .eslintrc.json's
 * extends: ["next/core-web-vitals", "next/typescript"] relied on `next lint`,
 * which is deprecated and, in this project, fails outright: its
 * eslintrc-to-flat-config bridging tries to JSON.stringify a config object
 * that eslint-plugin-react's own flat preset makes circular, throwing before
 * linting ever runs. eslint-config-next already ships real flat-config
 * arrays (see its "./core-web-vitals" and "./typescript" exports) -- using
 * those directly with the plain `eslint` CLI skips that broken bridging
 * entirely instead of working around it.
 */
/** @type {import("eslint").Linter.Config[]} */
const config = [
  {
    ignores: ["coverage/**", 
      ".next/**",
      "node_modules/**",
      "backend/**",
      // Generated by orval from api-spec/openapi.yaml -- not hand-edited, not worth linting.
      "src/api-client/generated/**",
      "src/api-zod/generated/**",
      // Vendored via the shadcn CLI, not hand-maintained to this project's style.
      "src/components/ui/**",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      /*
       * `const { department, ...rest } = ANSWERS` is how the survey tests build
       * an answer map with one key missing. The omitted binding is meant to be
       * unused -- that's the entire point of the pattern -- so flagging it just
       * pushes people toward uglier workarounds. ignoreRestSiblings exists for
       * exactly this case. Underscore-prefixed names are opted out too, for
       * deliberately-unused args and caught errors.
       */
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          ignoreRestSiblings: true,
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    /*
     * Bun's mock.module() is process-global and permanent, so two files each
     * installing their own factory for one module path is an order-dependent
     * bug: the tests pass in isolation and fail in the full run, and the fix is
     * far from the symptom. src/test/mock-module-registry.ts enforces one owner
     * per path at install time -- but only for calls that go through it, so
     * this rule keeps mock.module() out of every other file. See that module's
     * header for the "@/db" collision that motivated both.
     */
    files: ["**/*.ts", "**/*.tsx"],
    ignores: ["src/test/mock-module-registry.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.object.name='mock'][callee.property.name='module']",
          message:
            "Call installModuleMock() from @/test/mock-module-registry instead of mock.module() directly -- it enforces one mock factory per module path, which mock.module() alone cannot.",
        },
      ],
    },
  },
];

export default config;
