import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * Flat config (ESLint 9). The old .eslintrc.json's
 * extends: ["next/core-web-vitals", "next/typescript"] relied on `next lint`,
 * which is deprecated and, in this project, fails outright: its
 * eslintrc-to-flat-config bridging tries to JSON.stringify a config object
 * that eslint-plugin-react's own flat preset makes circular, throwing before
 * linting ever runs. eslint-config-next already ships real flat-config
 * arrays (see its "./core-web-vitals" and "./typescript" exports) -- using
 * those directly with the plain `eslint` CLI skips that broken bridging
 * entirely instead of working around it.
 */
/** @type {import("eslint").Linter.Config[]} */
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "backend/**",
      // Generated by orval from api-spec/openapi.yaml -- not hand-edited, not worth linting.
      "src/api-client/generated/**",
      "src/api-zod/generated/**",
      // Vendored via the shadcn CLI, not hand-maintained to this project's style.
      "src/components/ui/**",
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
];

export default config;
